alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_TYPE foreign key (TYPE_ID) references PETCLINIC_PET_TYPE(ID);
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID);
create unique index IDX_PETCLINIC_PET_ID_UNQ on PETCLINIC_PET (IDENTIFICATION_NUMBER, DELETE_TS) where DELETE_TS is null ;
create index IDX_PETCLINIC_PET_TYPE on PETCLINIC_PET (TYPE_ID);
create index IDX_PETCLINIC_PET_OWNER on PETCLINIC_PET (OWNER_ID);
